//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberPulse.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberPulse.Shared.Resources.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accepted Quantity.
        /// </summary>
        public static string AcceptedQuantity {
            get {
                return ResourceManager.GetString("AcceptedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrator.
        /// </summary>
        public static string Admi {
            get {
                return ResourceManager.GetString("Admi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrator Registration.
        /// </summary>
        public static string AdminRegister_ {
            get {
                return ResourceManager.GetString("AdminRegister.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert date.
        /// </summary>
        public static string AlertDate {
            get {
                return ResourceManager.GetString("AlertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The apprentices must amyor o igual a 1.
        /// </summary>
        public static string ApprenticeRange {
            get {
                return ResourceManager.GetString("ApprenticeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #Apprentices.
        /// </summary>
        public static string Apprentices {
            get {
                return ResourceManager.GetString("Apprentices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authorizing...
        /// </summary>
        public static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base value.
        /// </summary>
        public static string BaseValue {
            get {
                return ResourceManager.GetString("BaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Budget.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Budget course.
        /// </summary>
        public static string BudgetCourse {
            get {
                return ResourceManager.GetString("BudgetCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Budget lot.
        /// </summary>
        public static string BudgetLot {
            get {
                return ResourceManager.GetString("BudgetLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Budget lots.
        /// </summary>
        public static string BudgetLots {
            get {
                return ResourceManager.GetString("BudgetLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Budget program.
        /// </summary>
        public static string BudgetProgram {
            get {
                return ResourceManager.GetString("BudgetProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Budget programs.
        /// </summary>
        public static string BudgetPrograms {
            get {
                return ResourceManager.GetString("BudgetPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The amount entered will exceed the value of the rubro..
        /// </summary>
        public static string BudgetProgramWorth {
            get {
                return ResourceManager.GetString("BudgetProgramWorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Budgets.
        /// </summary>
        public static string Budgets {
            get {
                return ResourceManager.GetString("Budgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Budget type.
        /// </summary>
        public static string BudgetType {
            get {
                return ResourceManager.GetString("BudgetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Budgets type.
        /// </summary>
        public static string BudgetTypes {
            get {
                return ResourceManager.GetString("BudgetTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catgory.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cellular.
        /// </summary>
        public static string Cellular {
            get {
                return ResourceManager.GetString("Cellular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chip.
        /// </summary>
        public static string Chip {
            get {
                return ResourceManager.GetString("Chip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline.
        /// </summary>
        public static string ChipDecline {
            get {
                return ResourceManager.GetString("ChipDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute.
        /// </summary>
        public static string ChipExecute {
            get {
                return ResourceManager.GetString("ChipExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chip No.
        /// </summary>
        public static string ChipNo {
            get {
                return ResourceManager.GetString("ChipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter the token number before executing it..
        /// </summary>
        public static string ChipNoNull {
            get {
                return ResourceManager.GetString("ChipNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chip program.
        /// </summary>
        public static string ChipProgram {
            get {
                return ResourceManager.GetString("ChipProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chips.
        /// </summary>
        public static string Chips {
            get {
                return ResourceManager.GetString("Chips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        public static string ChipView {
            get {
                return ResourceManager.GetString("ChipView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Classe.
        /// </summary>
        public static string Classe {
            get {
                return ResourceManager.GetString("Classe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close validity.
        /// </summary>
        public static string CloseValidity {
            get {
                return ResourceManager.GetString("CloseValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure about {0} {1}?.
        /// </summary>
        public static string CloseValidityConfirm {
            get {
                return ResourceManager.GetString("CloseValidityConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for confirming your email, you can now log in to the system..
        /// </summary>
        public static string ConfirmedEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmedEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email confirmation.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press the button to confirm your account..
        /// </summary>
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordinator.
        /// </summary>
        public static string Coor {
            get {
                return ResourceManager.GetString("Coor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The form has been sent for validation..
        /// </summary>
        public static string CoordinatorInfo {
            get {
                return ResourceManager.GetString("CoordinatorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string CourseCode {
            get {
                return ResourceManager.GetString("CourseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Course and lots.
        /// </summary>
        public static string CourseProgramLot {
            get {
                return ResourceManager.GetString("CourseProgramLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Courses.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The end date must be after the start date..
        /// </summary>
        public static string DateNoEndStart {
            get {
                return ResourceManager.GetString("DateNoEndStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Star.
        /// </summary>
        public static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Morning Start.
        /// </summary>
        public static string DateStartMon {
            get {
                return ResourceManager.GetString("DateStartMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are your sure to delete the {0} {1}?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documente Id.
        /// </summary>
        public static string DocumentId {
            get {
                return ResourceManager.GetString("DocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit User Profile.
        /// </summary>
        public static string EditUserProfile {
            get {
                return ResourceManager.GetString("EditUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email you entered already exists..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email must be an allowed domain.
        /// </summary>
        public static string EmailDomainInvalid {
            get {
                return ResourceManager.GetString("EmailDomainInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instructor.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a not hours work.
        /// </summary>
        public static string EndDateError {
            get {
                return ResourceManager.GetString("EndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record not found..
        /// </summary>
        public static string ERR001 {
            get {
                return ResourceManager.GetString("ERR001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot be delete because it has releted records..
        /// </summary>
        public static string ERR002 {
            get {
                return ResourceManager.GetString("ERR002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record you are trying to create already exists..
        /// </summary>
        public static string ERR003 {
            get {
                return ResourceManager.GetString("ERR003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The country Id not valid..
        /// </summary>
        public static string ERR004 {
            get {
                return ResourceManager.GetString("ERR004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Supplier Id is not valid..
        /// </summary>
        public static string ERR005 {
            get {
                return ResourceManager.GetString("ERR005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect email or password.
        /// </summary>
        public static string ERR006 {
            get {
                return ResourceManager.GetString("ERR006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the maximum number of attempts, your account is blocked, please try again in 5 minutes..
        /// </summary>
        public static string ERR007 {
            get {
                return ResourceManager.GetString("ERR007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user has not been enabled, you must follow the instructions in the email sent to enable the user..
        /// </summary>
        public static string ERR008 {
            get {
                return ResourceManager.GetString("ERR008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This link is no longer available..
        /// </summary>
        public static string ERR009 {
            get {
                return ResourceManager.GetString("ERR009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid form data.
        /// </summary>
        public static string ERR010 {
            get {
                return ResourceManager.GetString("ERR010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Beginning of validity.
        /// </summary>
        public static string ERR011 {
            get {
                return ResourceManager.GetString("ERR011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a validity.
        /// </summary>
        public static string ERR012 {
            get {
                return ResourceManager.GetString("ERR012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current validity has no movements, you must create a movement or delete it..
        /// </summary>
        public static string ERR013 {
            get {
                return ResourceManager.GetString("ERR013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No active validity was found.
        /// </summary>
        public static string ERR014 {
            get {
                return ResourceManager.GetString("ERR014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are already products in this validity period.
        /// </summary>
        public static string ERR015 {
            get {
                return ResourceManager.GetString("ERR015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No products were found for the previous period.
        /// </summary>
        public static string ERR016 {
            get {
                return ResourceManager.GetString("ERR016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SQL internal error.
        /// </summary>
        public static string ERR017 {
            get {
                return ResourceManager.GetString("ERR017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The total amount exceeds the budget..
        /// </summary>
        public static string ERR018 {
            get {
                return ResourceManager.GetString("ERR018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Families.
        /// </summary>
        public static string Families {
            get {
                return ResourceManager.GetString("Families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have you forgotten your password?.
        /// </summary>
        public static string ForgottenYourPassword {
            get {
                return ResourceManager.GetString("ForgottenYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a holidays.
        /// </summary>
        public static string holidays {
            get {
                return ResourceManager.GetString("holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instructor.
        /// </summary>
        public static string Instructor {
            get {
                return ResourceManager.GetString("Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The course has been submitted; the instructor will receive an email notification..
        /// </summary>
        public static string InstructorCourseEmail {
            get {
                return ResourceManager.GetString("InstructorCourseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The instructor will be notified of the decision via email..
        /// </summary>
        public static string InstructorEjecutar {
            get {
                return ResourceManager.GetString("InstructorEjecutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The form has been sent, the instructor will receive an email to notify.
        /// </summary>
        public static string InstructorEmail {
            get {
                return ResourceManager.GetString("InstructorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program.
        /// </summary>
        public static string InvProgram {
            get {
                return ResourceManager.GetString("InvProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programs.
        /// </summary>
        public static string InvPrograms {
            get {
                return ResourceManager.GetString("InvPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value added taxes (I.V.A).
        /// </summary>
        public static string Ivas {
            get {
                return ResourceManager.GetString("Ivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justification.
        /// </summary>
        public static string Justification {
            get {
                return ResourceManager.GetString("Justification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to leave the page and lose your changes?.
        /// </summary>
        public static string LeaveAndLoseChanges {
            get {
                return ResourceManager.GetString("LeaveAndLoseChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to log out?.
        /// </summary>
        public static string LogoutConfirm {
            get {
                return ResourceManager.GetString("LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you log out, you will need to log back in to access your account..
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} must be between {2} and {1} characters..
        /// </summary>
        public static string LongthField {
            get {
                return ResourceManager.GetString("LongthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lot.
        /// </summary>
        public static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lots.
        /// </summary>
        public static string Lots {
            get {
                return ResourceManager.GetString("Lots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail Forwarding.
        /// </summary>
        public static string MailForwarding {
            get {
                return ResourceManager.GetString("MailForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} must have a maximum of {1} characters..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field must have at least {1} characters..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neighborhood.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neighborhoods.
        /// </summary>
        public static string Neighborhoods {
            get {
                return ResourceManager.GetString("Neighborhoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The are no program to select.
        /// </summary>
        public static string NoProgram {
            get {
                return ResourceManager.GetString("NoProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not records to show....
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are not autorized  to view this content...
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, there is nothing  on this route.
        /// </summary>
        public static string NothingInRoute {
            get {
                return ResourceManager.GetString("NothingInRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not a user yet? Register here.
        /// </summary>
        public static string NotUserYet {
            get {
                return ResourceManager.GetString("NotUserYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password and confirmation are noot the same..
        /// </summary>
        public static string PasswordAndConfirmationDifferent {
            get {
                return ResourceManager.GetString("PasswordAndConfirmationDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password changed successfully.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password confirm.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have at least one lowercase letter, one uppercase letter, one number, one special character (@$!%*?&amp;), and a minimum of 8 characters..
        /// </summary>
        public static string PasswordParameters {
            get {
                return ResourceManager.GetString("PasswordParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password changed successfully, you can now log in with your new password..
        /// </summary>
        public static string PasswordRecoveredMessage {
            get {
                return ResourceManager.GetString("PasswordRecoveredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password recovery.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a %.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait...
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prince High.
        /// </summary>
        public static string PriceHigh {
            get {
                return ResourceManager.GetString("PriceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prince Low.
        /// </summary>
        public static string PriceLow {
            get {
                return ResourceManager.GetString("PriceLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Priority bet.
        /// </summary>
        public static string PriorityBet {
            get {
                return ResourceManager.GetString("PriorityBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products %.
        /// </summary>
        public static string ProductAllPercentage {
            get {
                return ResourceManager.GetString("ProductAllPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current value.
        /// </summary>
        public static string ProductCurrentValue {
            get {
                return ResourceManager.GetString("ProductCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program and Lot.
        /// </summary>
        public static string ProgramLot {
            get {
                return ResourceManager.GetString("ProgramLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program and lots.
        /// </summary>
        public static string ProgramLots {
            get {
                return ResourceManager.GetString("ProgramLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pudget programs.
        /// </summary>
        public static string PudgetPrograms {
            get {
                return ResourceManager.GetString("PudgetPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchasing board.
        /// </summary>
        public static string Purc {
            get {
                return ResourceManager.GetString("Purc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The course materials have been sent, and the board will receive an email notification..
        /// </summary>
        public static string PurchasingBoardEmail {
            get {
                return ResourceManager.GetString("PurchasingBoardEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quoted 01.
        /// </summary>
        public static string Quoted01 {
            get {
                return ResourceManager.GetString("Quoted01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quoted 02.
        /// </summary>
        public static string Quoted02 {
            get {
                return ResourceManager.GetString("Quoted02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quoted 03.
        /// </summary>
        public static string Quoted03 {
            get {
                return ResourceManager.GetString("Quoted03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quoted value.
        /// </summary>
        public static string QuotedValue {
            get {
                return ResourceManager.GetString("QuotedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validity successfully closed..
        /// </summary>
        public static string RecordCloseValidityConfirmdOk {
            get {
                return ResourceManager.GetString("RecordCloseValidityConfirmdOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record create successfully..
        /// </summary>
        public static string RecordCreateOk {
            get {
                return ResourceManager.GetString("RecordCreateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record deleted successfully..
        /// </summary>
        public static string RecordDeletedOk {
            get {
                return ResourceManager.GetString("RecordDeletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record saved successfully..
        /// </summary>
        public static string RecordSavedOk {
            get {
                return ResourceManager.GetString("RecordSavedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RecordsNumbre.
        /// </summary>
        public static string RecordsNumber {
            get {
                return ResourceManager.GetString("RecordsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An email has been sent to you with instructions on how to recover your password..
        /// </summary>
        public static string RecoverPasswordMessage {
            get {
                return ResourceManager.GetString("RecoverPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register as new user.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Illegal characters.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excel.
        /// </summary>
        public static string ReportExcel {
            get {
                return ResourceManager.GetString("ReportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pdf.
        /// </summary>
        public static string ReportPdf {
            get {
                return ResourceManager.GetString("ReportPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requested quantity.
        /// </summary>
        public static string RequestedQuantity {
            get {
                return ResourceManager.GetString("RequestedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a lot.
        /// </summary>
        public static string RequiredLot {
            get {
                return ResourceManager.GetString("RequiredLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a rubro.
        /// </summary>
        public static string RequiredRubro {
            get {
                return ResourceManager.GetString("RequiredRubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value must be greater than zero.
        /// </summary>
        public static string RequiredWorth {
            get {
                return ResourceManager.GetString("RequiredWorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend account activation email.
        /// </summary>
        public static string ResendAccountActivationEmail {
            get {
                return ResourceManager.GetString("ResendAccountActivationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rubro.
        /// </summary>
        public static string Rubro {
            get {
                return ResourceManager.GetString("Rubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search...
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segment.
        /// </summary>
        public static string Segment {
            get {
                return ResourceManager.GetString("Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segments.
        /// </summary>
        public static string Segments {
            get {
                return ResourceManager.GetString("Segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a budget --.
        /// </summary>
        public static string SelectABudget {
            get {
                return ResourceManager.GetString("SelectABudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a budget program --.
        /// </summary>
        public static string SelectABudgetProgram {
            get {
                return ResourceManager.GetString("SelectABudgetProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select A Budget Type --.
        /// </summary>
        public static string SelectABudgetType {
            get {
                return ResourceManager.GetString("SelectABudgetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a chip program --.
        /// </summary>
        public static string SelectAChipProgram {
            get {
                return ResourceManager.GetString("SelectAChipProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select  a city --.
        /// </summary>
        public static string SelectACity {
            get {
                return ResourceManager.GetString("SelectACity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a classe --.
        /// </summary>
        public static string SelectAClasse {
            get {
                return ResourceManager.GetString("SelectAClasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a Country --.
        /// </summary>
        public static string SelectACountry {
            get {
                return ResourceManager.GetString("SelectACountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a course --.
        /// </summary>
        public static string SelectACourse {
            get {
                return ResourceManager.GetString("SelectACourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a family --.
        /// </summary>
        public static string SelectAFamily {
            get {
                return ResourceManager.GetString("SelectAFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select an instructor --.
        /// </summary>
        public static string SelectAInstructor {
            get {
                return ResourceManager.GetString("SelectAInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a iva --.
        /// </summary>
        public static string SelectAIva {
            get {
                return ResourceManager.GetString("SelectAIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a lot --.
        /// </summary>
        public static string SelectALot {
            get {
                return ResourceManager.GetString("SelectALot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a neighborhood --.
        /// </summary>
        public static string SelectANeighborhood {
            get {
                return ResourceManager.GetString("SelectANeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a product --.
        /// </summary>
        public static string SelectAProduct {
            get {
                return ResourceManager.GetString("SelectAProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a program --.
        /// </summary>
        public static string SelectAProgram {
            get {
                return ResourceManager.GetString("SelectAProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --Select a segment --.
        /// </summary>
        public static string SelectASegment {
            get {
                return ResourceManager.GetString("SelectASegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a state --.
        /// </summary>
        public static string SelectAState {
            get {
                return ResourceManager.GetString("SelectAState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Selecta statu --.
        /// </summary>
        public static string SelectAStatu {
            get {
                return ResourceManager.GetString("SelectAStatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a training program --.
        /// </summary>
        public static string SelectATrainingProgram {
            get {
                return ResourceManager.GetString("SelectATrainingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select training type --.
        /// </summary>
        public static string SelectATypeOfTraining {
            get {
                return ResourceManager.GetString("SelectATypeOfTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Selecta unit measurement --.
        /// </summary>
        public static string SelectAUnitMeasurement {
            get {
                return ResourceManager.GetString("SelectAUnitMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select a validity --.
        /// </summary>
        public static string SelectAValidity {
            get {
                return ResourceManager.GetString("SelectAValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a file....
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been created successfully. An email has been sent to you with instructions on how to activate your account..
        /// </summary>
        public static string SendEmailConfirmationMessage {
            get {
                return ResourceManager.GetString("SendEmailConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerts Sent Today.
        /// </summary>
        public static string SentAlert {
            get {
                return ResourceManager.GetString("SentAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a start date.
        /// </summary>
        public static string StartDateNull {
            get {
                return ResourceManager.GetString("StartDateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date.
        /// </summary>
        public static string StartsDate {
            get {
                return ResourceManager.GetString("StartsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a States.
        /// </summary>
        public static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statu.
        /// </summary>
        public static string Statu {
            get {
                return ResourceManager.GetString("Statu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stocktaking.
        /// </summary>
        public static string Stocktaking {
            get {
                return ResourceManager.GetString("Stocktaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sub Category.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instructor Sheet.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support Fic.
        /// </summary>
        public static string SupportFic {
            get {
                return ResourceManager.GetString("SupportFic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SENA - Arauca Region.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program.
        /// </summary>
        public static string TrainingProgram {
            get {
                return ResourceManager.GetString("TrainingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Training programs.
        /// </summary>
        public static string TrainingPrograms {
            get {
                return ResourceManager.GetString("TrainingPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trining level.
        /// </summary>
        public static string TriningLevel {
            get {
                return ResourceManager.GetString("TriningLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tursday.
        /// </summary>
        public static string Tursday {
            get {
                return ResourceManager.GetString("Tursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of training.
        /// </summary>
        public static string TypeOfTraining {
            get {
                return ResourceManager.GetString("TypeOfTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit measurement.
        /// </summary>
        public static string UnitMeasurement {
            get {
                return ResourceManager.GetString("UnitMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit of measurements.
        /// </summary>
        public static string UnitMeasurements {
            get {
                return ResourceManager.GetString("UnitMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code Unspsc.
        /// </summary>
        public static string Unspsc {
            get {
                return ResourceManager.GetString("Unspsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡You must update the form before submitting it!.
        /// </summary>
        public static string UpdateRow {
            get {
                return ResourceManager.GetString("UpdateRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload programs.
        /// </summary>
        public static string uploadFile {
            get {
                return ResourceManager.GetString("uploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Registration.
        /// </summary>
        public static string UserRegister {
            get {
                return ResourceManager.GetString("UserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The start time must be between 12:00 and 24:00.
        /// </summary>
        public static string ValidarRangoHora {
            get {
                return ResourceManager.GetString("ValidarRangoHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a valid email.
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validity.
        /// </summary>
        public static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value must be zero or greater.
        /// </summary>
        public static string ValueRange {
            get {
                return ResourceManager.GetString("ValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Worth.
        /// </summary>
        public static string Worth {
            get {
                return ResourceManager.GetString("Worth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value exceeds the budget of the program.
        /// </summary>
        public static string WorthExceedsProgramBudget {
            get {
                return ResourceManager.GetString("WorthExceedsProgramBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Worth Must Be Greater Than Zero.
        /// </summary>
        public static string WorthMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("WorthMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zip code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
